# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Roman\Desktop\Mirea\PR_Qt\PR3\main1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.csv_name = QtWidgets.QLineEdit(self.centralwidget)
        self.csv_name.setObjectName("csv_name")
        self.gridLayout_2.addWidget(self.csv_name, 0, 2, 1, 1)
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setObjectName("btn_load")
        self.gridLayout_2.addWidget(self.btn_load, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setKerning(False)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.addr_from = QtWidgets.QLineEdit(self.centralwidget)
        self.addr_from.setObjectName("addr_from")
        self.gridLayout.addWidget(self.addr_from, 1, 1, 1, 2)
        self.qweqweqw_2 = QtWidgets.QLabel(self.centralwidget)
        self.qweqweqw_2.setObjectName("qweqweqw_2")
        self.gridLayout.addWidget(self.qweqweqw_2, 2, 0, 1, 1)
        self.qweqweqw = QtWidgets.QLabel(self.centralwidget)
        self.qweqweqw.setObjectName("qweqweqw")
        self.gridLayout.addWidget(self.qweqweqw, 1, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setText("")
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.qweq = QtWidgets.QLabel(self.centralwidget)
        self.qweq.setObjectName("qweq")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.qweq)
        self.msg_subj = QtWidgets.QLineEdit(self.centralwidget)
        self.msg_subj.setObjectName("msg_subj")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.msg_subj)
        self.qweqwe = QtWidgets.QLabel(self.centralwidget)
        self.qweqwe.setObjectName("qweqwe")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.qweqwe)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        spacerItem1 = QtWidgets.QSpacerItem(350, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_send)
        self.msg_text = QtWidgets.QTextEdit(self.centralwidget)
        self.msg_text.setObjectName("msg_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.msg_text)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.formLayout)
        self.gridLayout_3.addLayout(self.formLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Приложение для отправления писем через CSV"))
        self.btn_load.setText(_translate("MainWindow", "Выбор"))
        self.label_2.setText(_translate("MainWindow", "Выбрать CSV файл       "))
        self.label.setText(_translate("MainWindow", "Сервер"))
        self.comboBox.setItemText(0, _translate("MainWindow", "mail"))
        self.comboBox.setItemText(1, _translate("MainWindow", "yandex"))
        self.comboBox.setItemText(2, _translate("MainWindow", "gmail"))
        self.addr_from.setText(_translate("MainWindow", "romaniy11052001@mail.ru"))
        self.qweqweqw_2.setText(_translate("MainWindow", "Пароль"))
        self.qweqweqw.setText(_translate("MainWindow", "Адрес отправителя"))
        self.qweq.setText(_translate("MainWindow", "Тема                    "))
        self.msg_subj.setText(_translate("MainWindow", "Практика 3 Горбунов РВ"))
        self.qweqwe.setText(_translate("MainWindow", "Текст сообщения"))
        self.btn_send.setText(_translate("MainWindow", "Отправить"))
        self.msg_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Текст для рассылки по CSV файлу</p></body></html>"))
