# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Roman\Desktop\Mirea\PR_Qt\PR6\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 771, 371))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 771, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sizesieze = QtWidgets.QLabel(self.widget)
        self.sizesieze.setObjectName("sizesieze")
        self.horizontalLayout.addWidget(self.sizesieze)
        self.size = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.size.setFont(font)
        self.size.setText("")
        self.size.setObjectName("size")
        self.horizontalLayout.addWidget(self.size)
        self.increase_font_action = QtWidgets.QPushButton(self.widget)
        self.increase_font_action.setObjectName("increase_font_action")
        self.horizontalLayout.addWidget(self.increase_font_action)
        self.decrease_font_action = QtWidgets.QPushButton(self.widget)
        self.decrease_font_action.setObjectName("decrease_font_action")
        self.horizontalLayout.addWidget(self.decrease_font_action)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fontComboBox = QtWidgets.QFontComboBox(self.widget)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout.addWidget(self.fontComboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.open = QtWidgets.QAction(MainWindow)
        self.open.setObjectName("open")
        self.menu.addAction(self.save)
        self.menu.addAction(self.open)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Текстовый редактор"))
        self.sizesieze.setText(_translate("MainWindow", "Раземер шрифта"))
        self.increase_font_action.setText(_translate("MainWindow", "Увеличить"))
        self.decrease_font_action.setText(_translate("MainWindow", "Уменьшить"))
        self.label_2.setText(_translate("MainWindow", "Шрифт"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.open.setText(_translate("MainWindow", "Открыть"))
