# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Roman\Desktop\Mirea\PR_Qt\PR1\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.qweqweqw = QtWidgets.QLabel(self.centralwidget)
        self.qweqweqw.setObjectName("qweqweqw")
        self.verticalLayout_2.addWidget(self.qweqweqw)
        self.qweq = QtWidgets.QLabel(self.centralwidget)
        self.qweq.setObjectName("qweq")
        self.verticalLayout_2.addWidget(self.qweq)
        self.qweqwe = QtWidgets.QLabel(self.centralwidget)
        self.qweqwe.setObjectName("qweqwe")
        self.verticalLayout_2.addWidget(self.qweqwe)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addr_to = QtWidgets.QLineEdit(self.centralwidget)
        self.addr_to.setObjectName("addr_to")
        self.verticalLayout.addWidget(self.addr_to)
        self.msg_subj = QtWidgets.QLineEdit(self.centralwidget)
        self.msg_subj.setObjectName("msg_subj")
        self.verticalLayout.addWidget(self.msg_subj)
        self.msg_text = QtWidgets.QTextEdit(self.centralwidget)
        self.msg_text.setObjectName("msg_text")
        self.verticalLayout.addWidget(self.msg_text)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.btn_send)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.qweqweqw.setText(_translate("MainWindow", "Адрес получателя"))
        self.qweq.setText(_translate("MainWindow", "Тема"))
        self.qweqwe.setText(_translate("MainWindow", "Текст сообщения"))
        self.addr_to.setText(_translate("MainWindow", "romaniy11052001@gmail.com"))
        self.msg_subj.setText(_translate("MainWindow", "Hello"))
        self.msg_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello!!!!!!!</p></body></html>"))
        self.btn_send.setText(_translate("MainWindow", "Отправить"))
